[[section-architecture-constraints]]
== Architecture Constraints

The constraints will be divided into business and technical.


=== Technical Constraints

These constraints will limit the team's ability to change the technology environment.

[options="header"]
|===
| Constraint        | Explanation
| TypeScript    | TypeScript is the programming language in which the project has to be implemented.
| React     | The application must be implemented using the React Framework.
| Github     |  The project must be constantly updated in GitHub, showing all the members collaborations.
| Arc42     | The documentation must follow the Arc42 templates.
| SOLID       | The project will user SOLID user pods as data retrieval.
| Continuous integration system | The practice of automating the integration of code changes from multiple contributors into a single software project
|===


=== Organizational Constraints

[options="header"]
|===
| Constraint        | Explanation
| Time    | The project must be done in 11 weeks.
| Team     | The team is composed of 6 members.

|===

[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****
