[[section-solution-strategy]]
== Solution Strategy

[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture.
These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture.
They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way, based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****

=== Technology Decisions

The technologies we have decided to use for the development of the app are:


Solid Community, Inrupt and SolidWeb  → Main POD server providers. Widely used. The app works with all the PODs that follows the same standard as them.

Firebase → Serverless service for the deployment and development of the application, providing the web and DB hosting,
a prepared backend for the DB and a way of deploying isolated custom functions. It also provides authentication storage,
so user's email and password (hashed) are safe and secure.

React and TypeScript have not been included in the list since it is compulsory to use them, and are not "a decision" itself.

=== Decisions about the top-level decomposition of the system

MVC → Probably the most common architectural pattern. It is used to decouple the interface, from the data and the domain logic.

=== Decisions on how to achieve key quality goals

**Privacy** → To achieve privacy, we won't store any personal data from our users apart from their past orders.

**Security** → As users need to log in in the application, we will store their user's passwords encrypted. Also, we plan to protect avery form field against SQL Injections by means of prepared statements.

**Availability** → Using an external reliable web-hosting service we ensure that the web and the database will be available almost 24/7.

=== Organizational decisions

To enable communication within the team members we have created a Discord Server for meetings and a Whatsapp chat
group in order to schedule those meetings. We have refined tasks in a GitHub project, so we can follow the overall work
and keep a backlog of the remaining tasks.

We also have an Issue system and a wiki, working as a log for decisions and minutes for meetings.


