[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****

[options="header"]
|===
| Decision         | Pros    | Cons
| QA-1 Webstorm      | Easy IDE to use very similar to IntellIJ |
| QA-2 Node.js   | Uses Javascript, you can stream big files.      | Do not provide scalability.
| QA-3 Webapp   | Better user experience, flexible access, easy setup.      | Reduced speed, Internet reliance.
| QA-4 Pod. Solid Community   | Data security, all data in one place.      | As the data is decentralized you need to rely on
a different product and poor documentation.
| QA-5 Firebase | It supports the development and the deployment for the app. Also some backend    | Not very familiarized
|===