[[section-quality-scenarios]]
== Quality Requirements

In this section our goal is to develop with more detail what it was said in the point 1.2, going in depth with the quality attributes.

[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.
****

=== Quality Tree

[plantuml, "Quality tree",png]
----
top-down direction
(System) as (S)
(Privacy) as (Pr)
(Security) as (Se)
(Availability) as (A)
(Usability) as (U)
(Maintainability) as (M)
(Resource utilization) as (R)
S --> Pr
S --> Se
S --> A
S --> U
S --> M
S --> R
----

[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.
****

=== Quality Scenarios

[%header, cols=3]
|===
|Quality requirement
|Quality scenario
|Priority

|Privacy
|Our users' data must be extremely protected. The lowest amount of data our application takes, the better. Of course, always taking into account a decentralized delivery.
|High

|Security
|We are going to give as much security as we can, saving the data in a safe way. We will try to prevent any kind of attack or leak.
|High

|Availability
|It is important to give the data to our users whenever they request, trying to reduce the technical failures to the minimal amount of time.
|Medium-High

|Usability
|Whenever the users want to access their information or to save new data, we want the to use our system in an easy way for them.
|Medium-High

|Maintainability
|Because our system will be in a constant develop and change, we want to design our implementation oriented to make this updates easier.
|Medium

|Resource utilization
|Our objective in this part is to use the available resources in an efficient way, trying to complete other goals optimizing the resources we have.
|Low-Medium

|===

[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****
