[[section-glossary]]
== Glossary



[role="arc42help"]
****
.Contents
The most important domain and technical terms that your stakeholders use when discussing the system.

You can also see the glossary as source for translations if you work in multi-language teams.

.Motivation
You should clearly define your terms, so that all stakeholders

* have an identical understanding of these terms
* do not use synonyms and homonyms

.Form
A table with columns <Term> and <Definition>.

Potentially more columns in case you need translations.

****

[options="header"]
|===
| Term         | Definition
| SOLID     | SOLID is a mnemonic acronym for five design principles,
                its main goal is to make code maintainable, understandable
                and extendable by means of those principles.
| TypeScript     | TypeScript is a strongly typed programming language
                    that builds on JavaScript.
| React     | React is an open-source JavaScript library designed for building
                user interfaces.
| Pod       | A Pod is a representation of the minimum objects that can be implemented
                in Kubernetes, it is a unique instance of a process running in
                your cluster.
| Node.js       | Node.js is a platform built on JavaScript runtime for easily building
                    fast and scalable network applications.
| Azure     | Azure is a cloud computing service operated by Microsoft for application
                management via Microsoft-managed data centers.
| MySQL     | MySQL is an open-source relational database management system.
|===
