[[section-glossary]]
== Glossary



[role="arc42help"]
****
.Contents
The most important domain and technical terms that your stakeholders use when discussing the system.

You can also see the glossary as source for translations if you work in multi-language teams.

.Motivation
You should clearly define your terms, so that all stakeholders

* have an identical understanding of these terms
* do not use synonyms and homonyms

.Form
A table with columns <Term> and <Definition>.

Potentially more columns in case you need translations.

****

[options="header"]
|===
| Term         | Definition
| Solid     | Solid is a specification that lets people store their data
                securely in decentralized data stores called Pods.
| TypeScript     | TypeScript is a strongly typed programming language
                    that builds on JavaScript.
| React     | React is an open-source JavaScript library designed for building
                user interfaces.
| Pod       | Pods are where you store your data. Any kind of data can be stored in a Solid Pod. Once stored in a Pod, you control who can access your data.
                
| Node.js       | Node.js is a platform built on JavaScript runtime for easily building
                    fast and scalable network applications.
| Azure     | Azure is a cloud computing service operated by Microsoft for application
                management via Microsoft-managed data centers.
| MySQL     | MySQL is an open-source relational database management system.
|===
